.SH ddctool(1) \-\- query and change monitor settings
.SS SYNOPSIS
.PP
\f[C]ddctool\f[] command [] []
.SS DESCRIPTION
.PP
Full bloody description goes here
.SS EXAMPLES
.PP
To identify monitors:
.PP
ddctool detect
.PP
To show all settings that the monitor supports and that \f[C]ddctool\f[]
understands:
.PP
ddctool getvcp supported
.PP
To set the luminosity value of the second monitor:
.PP
ddctool setvcp 10 30 \-\-display 2
.PP
To list all VCP features that \f[C]ddctool\f[] understands:
.PP
ddctool listvcp
.SS DIAGNOSTICS
.PP
Returns 0 on success, 1 on failure.
.PP
Requesting help is regarded as success.
.SS AUTHOR
.PP
Sanford Rockowitz 
