#!/bin/sh

# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# echo $DIR

# Old Way 
# rm -rf fedrev_temp/*
# mkdir -p fedrev_temp
# cp -p ddcutil.spec                  fedrev_temp
# cp -p built_rpms/ddcutil-*src.rpm   fedrev_temp
# cp -p built_rpms/x86_64/ddcutil*rpm fedrev_temp
# cd fedrev_temp
# fedora-review --mock-config fedora-rawhide-x86_64 -n ddcutil
# exit 


# Newer way:

rm -rf fedrev_work/*
mkdir -p fedrev_work

rm -f built_rpms/ddcutil-*.src.rpm
echo 
echo "--> Call fsrcrpm:"
make fsrcrpm
# assumes there's exactly 1 src rpm in built_rpms:
srpm=`ls built_rpms/ddcutil-*.src.rpm`
# echo $srpm
fqsrpm=${PWD}/${srpm}
# echo $fqsrpm
cd fedrev_work
mock_config=fedora-rawhide-x86_64

# does not solve problem of dirs in package also owned by libddcutil-devel
# cmd="mock -r ${mock_config} --init"
# echo
# echo "--> Executing $cmd"
# $cmd

cmd="fedora-review --mock-config ${mock_config} -rn ${fqsrpm}"
echo
echo "--> Executing $cmd"
$cmd
exit



# New Way 

rm -rf fedrev_temp/*
mkdir -p fedrev_temp

make fsrcrpm

cp -p built_rpms/ddcutil-*src.rpm   fedrev_temp
cd fedrev_temp
srpm=`ls ddcutil-*.src.rpm`
echo $srpm
fedora-review --mock-config fedora-rawhide-x86_64 -rn ${PWD}/${srpm}

