#!/bin/sh

# srcdir=/shared/playproj/i2c
# workdir=.


name=ddcutil 
# ver="0.2.4"
ver=$1
rlse=$2

echo "(upload_obsdeb) parm 0 = $0"
echo "(upload_obsdeb) parm 1 = $1, ver=${ver}"
echo "(upload_obsdeb) parm 2 = $2, rlse=${rlse}"
echo "(upload_obsdeb) parm 3 = $3"

obs_proj="home:rockowitz"
obs_pkg=ddcutil

[ $# -ge 3 ] && obs_pkg=$3

echo "(upload_obsdeb) obs_pkg=${obs_pkg}"

srcdir=${PWD}/..
curdir=${PWD}
workdir=${PWD}/obswork
debdir=${PWD}/debwork

echo srcdir=$srcdir
echo workdir=$workdir

# TODO: error if workdir exists but not a directory

if [ ! -d $workdir ]; then
	echo "(upload_obsdeb) creating $workdir"
  mkdir $workdir
else
	echo "(upload_obsdeb) clearing $workdir"
  rm -r $workdir/*
  rm -r $workdir/.osc
fi

cmd="osc checkout -o $workdir $obs_proj $obs_pkg"
echo "cmd: $cmd"
$cmd



# tar_fn=ddcutil-${ver}.tar.gz

# tar_fn_new=
# if [ -e $workdir/$tar_fn ]; then
#   echo "$tar_fn already exists"
# else 
#   echo "$tar_fn not checked out"
#   tar_fn_new=1
# fi

# Remove all prior versions - build will fail if they're still there

# doesn't work
# delfiles() {
#    echo delfiles: $1
#    for file in $1; do
#       echo delfiles: f: $f
#    done
# }

# echo Deleting ddcutil_*.orig.tar.gz
# echo Deleting ddcutil_*.
# rm ddcutil_*.orig.tar.gz
# rm ddcutil_*.debian.tar.xz
# rm ddcutil_*.dsc

cd $workdir

# delfiles ddcutil_*.orig.tar.gz

# Not needed, keep old files

# for f in ddcutil_*.orig.tar.gz; do
# 	echo "(upload_obsdeb) Deleting file: $f"
#    rm $f
# done

# for f in ddcutil_*.debian.tar.xz; do
# 	echo "(upload_obsdeb) Deleting file: $f"
#    rm $f
# done

# for f in ddcutil_*.dsc; do
#    echo "Deleting file: $f"
#    rm $f
# done

fn1="ddcutil_${ver}.orig.tar.gz"        
fn2="ddcutil_${ver}-${rlse}.debian.tar.xz"
fn3="ddcutil_${ver}-${rlse}.dsc"    

echo "Adding file: ${fn1}" 
cp -p $debdir/$fn1  .
echo "Adding file: ${fn2}" 
cp -p $debdir/$fn2  .
echo "Adding file: ${fn3}" 
cp -p $debdir/$fn3  .

osc addremove

# echo "fn1=${fn1}"
# echo "fn2=${fn2}"
# echo "fn3=${fn3}"

# cmd="osc commit ${fn1} ${fn2} ${fn3} --message=\"new deb build files\""
cmd="osc commit  -m \"new debian build files for package ${obs_pkg}\""

echo "cmd: ${cmd}"
$cmd

echo "Files in package ${obs_pkg} after osc commit:"
cmd="osc ls -l ${obs_proj} ${obs_pkg}"
$cmd


# osc rebuild
