#!/bin/sh
# TODO: Converge with upload_mentors, should be just one file
echo "Executing $0"

echo "(upload_mentors) executing"
if [ $# -lt 2 ]; then
   echo "Syntax: upload_mentors <ddcutil-version> <debian-release-number>"
   exit 1
fi

# ver="0.2.4"
ver=$1
rlse=$2

echo "(upload_mentors) parm 1 = $1, ver=${ver}"
echo "(upload_mentors) parm 2 = $2, rlse=${rlse}"

debdir=${PWD}/debwork
echo "(upload_mentors) debdir=${debdir}"
    
fn1="ddcutil_${ver}-${rlse}_source.changes"    
echo "(upload_mentors) fn1=${fn1}"

# cmd="debsign ${debdir}/${fn1}"
# echo "cmd: ${cmd}"
# $cmd

# echo "passphrase is ief..."
# cmd="dput  ppa:rockowitz/ddcutil ${debdir}/${fn1}"
cmd="dput --force mentors:rockowitz@minsoft.com ${debdir}/${fn1}"
echo "(upload_mentors) cmd: ${cmd}"
$cmd